variables:
  DOCKER_HOST: tcp://docker:2375/
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "" 
  POSTGRES_ENABLED: "false"
  TEST_DISABLED: "true" 


# build development

build_dev:
include:
  - template: Auto-DevOps.gitlab-ci.yml

  image: docker/compose:latest
  stage: build
  services:
    - name: docker:dind
      command: ["--mtu=1450"]
  tags:
    - cluster
  before_script:
    - sh -c 'cat .${CI_COMMIT_REF_SLUG}.env >> Dockerfile'

  script:
    - export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
    - export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG .
    - docker push $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master-dev"'

# deploy development
deploy-dev:
  stage: deploy
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:latest"
  variables:
    HELM_UPGRADE_EXTRA_ARGS: '--set ingress.tls.enabled=false --set service.externalPort=80 --set service.internalPort=80'
    DATABASE_URL: 'mysql://dhregistry:${DB_PASS}@helios.arz.oeaw.ac.at/dev-dhregistry?encoding=utf8&timezone=UTC&cacheMetadata=true&quoteIdentifiers=false&persistent=false'
  script:
    - auto-deploy check_kube_domain
    - auto-deploy download_chart
    - auto-deploy ensure_namespace
    - auto-deploy initialize_tiller
    - auto-deploy create_secret
    - auto-deploy deploy
    - auto-deploy delete canary
    - auto-deploy delete rollout
    - auto-deploy persist_environment_url
  environment:
    name: dhcr-dev
    url: https://dev-dhcr.clarin-dariah.eu
    kubernetes:
      namespace: dhcr-dev

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master-dev"'



# build production
build-prod:
include:
  - template: Auto-DevOps.gitlab-ci.yml
  image: docker/compose:latest
  stage: build
  services:
    - name: docker:dind
      command: ["--mtu=1450"]
  tags:
    - cluster
  
  before_script:
    - sh -c 'cat .${CI_COMMIT_REF_SLUG}.env >> Dockerfile'
  
  script:
    - export CI_APPLICATION_REPOSITORY=${CI_APPLICATION_REPOSITORY:-$CI_REGISTRY_IMAGE/$CI_COMMIT_REF_SLUG}
    - export CI_APPLICATION_TAG=${CI_APPLICATION_TAG:-$CI_COMMIT_SHA}
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - docker build -t $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG .
    - docker push $CI_APPLICATION_REPOSITORY:$CI_APPLICATION_TAG
  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'

# deploy production
deploy-prod:
  stage: deploy
  image: "registry.gitlab.com/gitlab-org/cluster-integration/auto-deploy-image:latest"
  variables:
    KUBE_NAMESPACE: dhcr-prod
    HELM_UPGRADE_EXTRA_ARGS: '--set ingress.tls.enabled=false --set service.externalPort=80 --set service.internalPort=80 --set service.url=dhcr.clarin-dariah.eu'
  script:
    - auto-deploy check_kube_domain
    - auto-deploy download_chart
    - auto-deploy ensure_namespace
    - auto-deploy initialize_tiller
    - auto-deploy create_secret
    - auto-deploy deploy
    - auto-deploy delete canary
    - auto-deploy delete rollout
    - auto-deploy persist_environment_url
  environment:
    name: dhcr-prod
    url: https://dhcr.clarin-dariah.eu
  artifacts:
    paths: [environment_url.txt, tiller.log]
    when: always

  rules:
    - if: '$CI_COMMIT_REF_NAME == "master"'
